table MBA
	lineageTag: 5e81dece-6a53-4852-99e1-6cfc7162fb60

	column Product_A
		dataType: string
		lineageTag: 714f8b31-e27b-42f3-b4da-0c7ac4c57853
		summarizeBy: none
		sourceColumn: Product_A

		annotation SummarizationSetBy = Automatic

	column Product_B
		dataType: string
		lineageTag: 65027792-d995-4837-ae29-343c00588a96
		summarizeBy: none
		sourceColumn: Product_B

		annotation SummarizationSetBy = Automatic

	column 'Support %'
		dataType: double
		lineageTag: bd020d86-5f43-4b3d-a01f-c99e2b2f815e
		summarizeBy: sum
		sourceColumn: Support %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Confidence %'
		dataType: double
		lineageTag: 9255942e-74b5-4a4f-b58e-0a2f4f4fe50e
		summarizeBy: sum
		sourceColumn: Confidence %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Lift
		dataType: double
		lineageTag: 0850823b-e3a2-4aaa-aa0b-65fa9c7bc955
		summarizeBy: sum
		sourceColumn: Lift

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Prefix
		dataType: string
		lineageTag: 3b38057c-d9c5-48df-8cfc-3cf21bcb09e6
		summarizeBy: none
		sourceColumn: Prefix

		annotation SummarizationSetBy = Automatic

	partition MBA = m
		mode: import
		queryGroup: main
		source =
				let
				    Source = Csv.Document(File.Contents("E:\DA\DA\PBI2 - RFM\Dataset\ProductPairs_MBA.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product_A", type text}, {"Product_B", type text}, {"Support %", type number}, {"Confidence %", type number}, {"Lift", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Lift] <> 0.85 and [Lift] <> 0.88 and [Lift] <> 0.9 and [Lift] <> 0.93 and [Lift] <> 0.99 and [Lift] <> 1)),
				    #"Added Index" = Table.AddIndexColumn(#"Filtered Rows", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Rule_Index_Main"}}),
				    #"Added Index1" = Table.AddIndexColumn(#"Renamed Columns", "Index", 1, 1, Int64.Type),
				    #"Inserted Prefix" = Table.AddColumn(#"Added Index1", "Prefix", each "Rule " & Text.From([Index], "en-US"), type text),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Prefix",{"Index"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"Prefix", "Product_A", "Product_B", "Support %", "Confidence %", "Lift", "Rule_Index_Main"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns",{"Rule_Index_Main"})
				in
				    #"Removed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

