table dim_customer
	lineageTag: 06815e23-efb4-4ce1-b88a-3a06fdb96dc1

	column TypeOfCustomers
		dataType: string
		lineageTag: 2012113c-7bb5-49bf-8d96-7419623a6922
		summarizeBy: none
		sourceColumn: TypeOfCustomers

		annotation SummarizationSetBy = Automatic

	column NCustomerID
		dataType: string
		lineageTag: 8f50aff1-b233-49f6-9494-3041b024da7c
		summarizeBy: none
		sourceColumn: NCustomerID

		annotation SummarizationSetBy = Automatic

	/// Ngày mua cuối cùng của khách hàng (không tính GUEST)
	column Customer_Last_Purchase_Date = IF(LEFT('dim_customer'[NCustomerID], 6) = "GUEST_", BLANK(), MAXX(FILTER(fact_sales, 'fact_sales'[CustomerID] = 'dim_customer'[NCustomerID]), 'fact_sales'[InvoiceDate]))
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: ddead2f1-24e0-406f-ac2e-fe69b38bb716
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 3427f885-9f29-4fdd-ab68-68b945262d84
			defaultHierarchy: LocalDateTable_db8497a2-868e-4b98-a0b8-722c0d114105.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Số ngày kể từ lần mua cuối (không tính GUEST)
	column Customer_Recency_Days = IF(LEFT(dim_customer[NCustomerID], 6) = "GUEST_", BLANK(), DATEDIFF(dim_customer[Customer_Last_Purchase_Date], MAX(fact_sales[InvoiceDate]), DAY))
		dataType: int64
		formatString: #,##0
		lineageTag: 6ee163c8-e17b-4923-b1cd-18620f92728c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"dim_customer","TableItemName":"Customer_Recency_Days (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	/// Mức Recency: H (< 2 tháng), M (2-4 tháng), L (> 4 tháng)
	column R_Level = IF(LEFT(dim_customer[NCustomerID], 6) = "GUEST_", BLANK(), IF(dim_customer[Customer_Recency_Days] < 60, "H", IF(dim_customer[Customer_Recency_Days] <= 120, "M", "L")))
		dataType: string
		lineageTag: 6276cbad-add7-4a5f-94aa-1c88ad5d7eb5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Số lần mua hàng (không tính GUEST)
	column Customer_Purchase_Count = IF(LEFT('dim_customer'[NCustomerID], 6) = "GUEST_", BLANK(), CALCULATE(DISTINCTCOUNT('fact_sales'[InvoiceNo]),fact_sales[Quantity] > 0))
		dataType: int64
		formatString: #,##0
		lineageTag: da0f6b87-cde0-4abc-b835-82256aa2705a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Tổng chi tiêu khách hàng (không tính GUEST)
	column Customer_Total_Revenue = ```
			
			IF(
			    LEFT('dim_customer'[NCustomerID], 6) = "GUEST_", 
			    BLANK(), 
			    CALCULATE(SUM('fact_sales'[Revenue]))
			)
			```
		dataType: decimal
		formatString: #,##0.00
		lineageTag: f0763d90-b7a8-480e-be80-e7696ce7a60d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Mức Frequency (H = top 1/3 mua nhiều nhất)
	column F_Level = ```
			
			IF(
			    LEFT('dim_customer'[NCustomerID], 6) = "GUEST_", 
			    BLANK(), 
			    VAR f_val = 'dim_customer'[Customer_Purchase_Count]
			    VAR valid_customers = FILTER(ALL('dim_customer'), LEFT('dim_customer'[NCustomerID], 6) <> "GUEST_") 
			    VAR p67 = PERCENTILEX.INC(valid_customers, 'dim_customer'[Customer_Purchase_Count], 0.67)
			    VAR p33 = PERCENTILEX.INC(valid_customers, 'dim_customer'[Customer_Purchase_Count], 0.33)
			    
			    RETURN 
			    IF(f_val > p67, "H", 
			        IF(f_val >= p33, "M", "L")
			    )
			)
			```
		dataType: string
		lineageTag: 0c062245-6469-48f9-a6f8-df6f4c6ef3d3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Mức Monetary (H = top 1/3 chi tiêu cao nhất)
	column M_Level = ```
			
			IF(
			    LEFT('dim_customer'[NCustomerID], 6) = "GUEST_", 
			    BLANK(), 
			    VAR m_val = 'dim_customer'[Customer_Total_Revenue]
			    VAR valid_customers = FILTER(ALL('dim_customer'), LEFT('dim_customer'[NCustomerID], 6) <> "GUEST_" && NOT(ISBLANK('dim_customer'[Customer_Total_Revenue])))
			    VAR p67 = PERCENTILEX.INC(valid_customers, 'dim_customer'[Customer_Total_Revenue], 0.67)
			    VAR p33 = PERCENTILEX.INC(valid_customers, 'dim_customer'[Customer_Total_Revenue], 0.33)
			    RETURN 
			    IF(m_val > p67, "H", 
			        IF(m_val >= p33, "M", "L")
			    )
			)
			```
		dataType: string
		lineageTag: 56e9d79e-3f48-41f5-ae94-29369ce954f0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Phân loại RFM: Champions, Loyal, At Risk, Lost (N/A cho GUEST)
	column RFM_Segment = ```
			
			IF(
			    LEFT('dim_customer'[NCustomerID], 6) = "GUEST_", 
			    "Guests",
			    VAR rfm = 'dim_customer'[R_Level] & 'dim_customer'[F_Level] & 'dim_customer'[M_Level]
			    
			    RETURN
			    SWITCH( rfm,
			        "HHH", "Champions",
			        "HHM", "Potential Loyalists",
			        "HMH", "Potential Loyalists",
			        "HMM", "Potential Loyalists",
			        "MHH", "Potential Loyalists",
			        "MHM", "Potential Loyalists",
			        "MMH", "Potential Loyalists",
			        "HML", "At Risk",
			        "LHH", "At Risk",
			        "LHM", "At Risk",
			        "LHL", "At Risk",
			        "LMH", "At Risk",
			        "LMM", "At Risk",
			        "LLH", "At Risk",
			        "MMM", "At Risk",
			        "MML", "At Risk",
			        "MLM", "At Risk",
			        "LLM", "Lost",
			        "LML", "Lost",
			        "LLL", "Lost",
			        "MLL", "Lost",
			        "HLL", "New/Others",
			        "HLM", "New/Others",
			        "HLH", "New/Others",
			        "MHL", "New/Others",
			        "MLH", "New/Others",
			        
			        "Others"
			    )
			)
			```
		dataType: string
		lineageTag: a719f995-b009-4a07-842d-90911bd55a5d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Customer_Recency_Days (bins)' =
			VAR __Count = 10
			
			VAR __Min = MIN('dim_customer'[Customer_Recency_Days])
			
			VAR __Max = MAX('dim_customer'[Customer_Recency_Days])
			
			VAR __Difference = (__Max - __Min)
			
			VAR __Size = IF(__Difference > 0, __Difference / __Count, 1)
			
			VAR __BinNumber = INT(('dim_customer'[Customer_Recency_Days] - __Min) / __Size)
			
			RETURN
				IF(
					ISBLANK('dim_customer'[Customer_Recency_Days]),
					BLANK(),
					__Min + (MIN(__BinNumber, __Count - 1) * __Size)
				)
		lineageTag: 3685cabc-4446-454a-a89a-7a8a9d441713
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "dim_customer"
				          }
				        },
				        "Property": "Customer_Recency_Days"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"d","Entity":"dim_customer"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"Customer_Recency_Days"}}],"BinItem":{"Expression":{"Member":{"Expression":{"Discretize":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"Customer_Recency_Days"}},"Count":10}},"Member":"Min"}}}}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Customer_First_Purchase_Date = IF(LEFT(dim_customer[NCustomerID],6) = "GUEST_",BLANK(),CALCULATE(MIN(fact_sales[InvoiceDate]),ALLEXCEPT(dim_customer,dim_customer[NCustomerID])))
		formatString: General Date
		lineageTag: a57b523c-72c2-4e6a-a3eb-fec6bc0331a4
		summarizeBy: none

		variation Variation
			isDefault
			relationship: d3495c37-5dca-40aa-8b25-87ee01ee390e
			defaultHierarchy: LocalDateTable_65161598-3c73-4142-a7be-fb87bae7e947.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Customer_First_Purchase_Month = FORMAT(dim_customer[Customer_First_Purchase_Date],"MMM YYYY")
		lineageTag: f9bd7f8c-970b-4455-a7a4-9be256e252f1
		summarizeBy: none
		sortByColumn: Month_Sorting

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Customer_Lifetime_Month = DATEDIFF(STARTOFMONTH(dim_customer[Customer_First_Purchase_Date]),STARTOFMONTH(dim_customer[Customer_Last_Purchase_Date]),MONTH)
		formatString: 0
		lineageTag: 359fb47c-21c5-4f54-89c2-b9d423905fe6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Month_Sorting = MONTH(dim_customer[Customer_First_Purchase_Date]) + YEAR(dim_customer[Customer_First_Purchase_Date])*100
		formatString: 0
		lineageTag: dc9c026e-51cb-4abd-a093-3da17abb559d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition dim_customer = m
		mode: import
		queryGroup: main
		source =
				let
				    Source = OnlineRetail,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"InvoiceNo", "CustomerID", "TypeOfCustomers"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "NCustomerID", each if [CustomerID] = "Guests/Unknown" then "GUEST_" & [InvoiceNo] else Text.From([CustomerID])),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"CustomerID", "InvoiceNo"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Duplicates",{"NCustomerID", "TypeOfCustomers"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

