table fact_sales
	lineageTag: e1c2b46f-597a-449a-9240-f9663bb39b9d

	column InvoiceNo
		dataType: string
		lineageTag: 63531fc9-b06a-46c7-95a7-8178e0dce7d5
		summarizeBy: none
		sourceColumn: InvoiceNo

		annotation SummarizationSetBy = Automatic

	column Product-SKU
		dataType: string
		lineageTag: a4c9d9e5-7415-4669-bcf4-c6dc20fc183e
		summarizeBy: none
		sourceColumn: Product-SKU

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: c33c3094-71e8-4f35-82fc-ed2dc6e44f65
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: e27c2755-c88e-42ea-83b7-65c1092f02cc
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column InvoiceDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: b2eb1a24-1518-4d76-96ce-28f9338cddb4
		summarizeBy: none
		sourceColumn: InvoiceDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Revenue
		dataType: double
		lineageTag: 9eacab7f-f87a-42f1-8544-d30c5ffcdc5b
		summarizeBy: sum
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustomerID
		dataType: string
		lineageTag: 12babfbd-9e79-46dd-a676-596b536085ac
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 91e36ce5-6cfb-4ffb-91df-84ad7ebc3d8a
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'UK or Others' = IF(fact_sales[Country] = "United Kingdom","UK","International")
		lineageTag: dd83eb55-3659-4532-b2f2-81621930d9a4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Cohort_Month = ```
			STARTOFMONTH(dim_customer[Customer_First_Purchase_Date]) 
			```
		formatString: General Date
		lineageTag: 6bae3904-fe50-49a9-8f59-69d210c0d491
		summarizeBy: none

		variation Variation
			isDefault
			relationship: d425d43e-4b43-4d7c-b5b6-240fa2c3c364
			defaultHierarchy: LocalDateTable_994e232c-4182-43eb-8097-037bf554fdd1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Transaction_Month = IF(LEFT(fact_sales[CustomerID],6)="GUEST_",BLANK(),STARTOFMONTH(fact_sales[InvoiceDate]))
		formatString: General Date
		lineageTag: add9c3fc-ac0b-4437-a182-8f22aeb663d6
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 18ec3c25-f18e-4aa8-abae-bf40add7fb84
			defaultHierarchy: LocalDateTable_8a5034f4-0f18-4983-8f03-2940bee11bc7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Month_Index = DATEDIFF(fact_sales[Cohort_Month],fact_sales[Transaction_Month],MONTH)
		formatString: 0
		lineageTag: 08d4801d-ca89-4b1d-9c73-aeacd85f91e4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Customer_Status_Type = ```
			
			VAR FirstMonth = 'fact_sales'[Cohort_Month]
			VAR CurrentMonth = fact_sales[Transaction_Month]
			RETURN
			    IF (
			        LEFT('fact_sales'[CustomerID], 6) = "GUEST_", 
			        "Guest",
			        IF ( 
			            CurrentMonth = FirstMonth, 
			            "New Customer", 
			            "Returning Customer" 
			        )
			    )
			```
		lineageTag: 1f3e8cf2-63f8-4e2c-9a58-5afffef79882
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Month_Sort = ```
			YEAR(fact_sales[Transaction_Month])*100 + MONTH(fact_sales[Transaction_Month]) 
			```
		formatString: 0
		lineageTag: 26d3c77a-b0a3-4ee6-92b6-2c04c36c1427
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fact_sales = m
		mode: import
		queryGroup: main
		source =
				let
				    Source = OnlineRetail,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Description", "TypeOfCustomers"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"InvoiceNo", "StockCode", "ProductVariant", "CustomerID", "UnitPrice", "Quantity", "InvoiceDate"}),
				    #"Added Revenue" = Table.AddColumn(#"Reordered Columns", "Revenue", each [Quantity] * [UnitPrice]),
				    #"Created Product - SKU" = Table.AddColumn(#"Added Revenue", "Product-SKU", each [StockCode]& "-" &[ProductVariant]),
				    #"Removed Descriptive Data 2" = Table.RemoveColumns(#"Created Product - SKU",{"StockCode", "ProductVariant"}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Descriptive Data 2",{"InvoiceNo", "CustomerID", "Product-SKU", "UnitPrice", "Quantity", "InvoiceDate", "Revenue"}),
				    #"Create new CustomerID" = Table.AddColumn(#"Reordered Columns1", "Custom", each if [CustomerID] = "Guests/Unknown" then "GUEST_" & [InvoiceNo] else Text.From([CustomerID])),
				    #"Removed old CustomerID" = Table.RemoveColumns(#"Create new CustomerID",{"CustomerID"}),
				    #"Reordered Columns2" = Table.ReorderColumns(#"Removed old CustomerID",{"InvoiceNo", "Product-SKU", "Custom", "UnitPrice", "Quantity", "InvoiceDate", "Revenue"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns2",{{"Custom", "CustomerID"}}),
				    #"Reordered Columns3" = Table.ReorderColumns(#"Renamed Columns",{"InvoiceNo", "Product-SKU", "CustomerID", "Country", "UnitPrice", "Quantity", "InvoiceDate", "Revenue"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Reordered Columns3",{{"Revenue", type number}, {"InvoiceDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

